### ISSUE TITLE
swap

### ISSUE THREAD

**Issue by akshay-** [pedja1/Kernel-Tuner#8]
i have installed this app and created a swap for 1000mb , and when i uninstalled this app it doesnt show where th swap file is created, it created swap file in my phones internal memory but i could not find this swap file, i want to delete that file as my phones internal memory is low, and the main thing when i give free command in terminal emulator, it doesnt show swap
my phone is Micromax A110 canvas 2
plz help
regards!

**Comment by pedja1** [comment]
New version doesn't support swap, and I probably won't. Old version is no longer maintained
